version: "3.7"
services:
  db:
    image: postgres:15
    container_name: postgres
    command:
      -p 5432
    expose:
      - 5432
    env_file:
      - .env-prod
  redis:
    image: redis:7
    container_name: redis_app
    command:
      --port 5370
    expose:
      - 5370
  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: fastapi_app
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis
    command: ["/fastapi_app/docker/app.sh"]
  celery:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: celery_app
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: flower_app
    command: ["/fastapi_app/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555
